default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: unique-nested-app_development

test:
  <<: *default
  database: unique-nested-app_test

production:
  <<: *default
  database: unique-nested-app_production
  username: unique-nested-app
  password: <%= ENV['UNIQUE_NESTED_APP_DATABASE_PASSWORD'] %>
